const $=id=>document.getElementById(id); let db;
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('RefuelDB',1);r.onupgradeneeded=e=>{e.target.result.createObjectStore('tx',{keyPath:'id'})};r.onsuccess=e=>{db=e.target.result;res(db)};r.onerror=rej})}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active'); if(id==='history') render();}
function startShift(){if(!$('fuelman').value.trim())return alert('Isi nama Fuelman.');localStorage.setItem('shift',JSON.stringify({fuelman:$('fuelman').value.trim(),shift:$('shift').value,truck:$('truck').value}));show('tx')}
['pUnit','pHm','pZero','pEnd'].forEach(id=>$(id).addEventListener('change',()=>{$('s'+id.slice(1)).textContent=$(id).files[0]?'SIAP ✓':'BELUM';$('s'+id.slice(1)).style.color='#4ade80'}));
function calc(){let b=parseFloat($('before').value)||0,c=parseFloat($('current').value)||0,f=parseFloat($('flowEnd').value)||0;let d=c-b,a=d>0?f/d:0;$('calc').innerHTML=`Total HM/KM: <b>${d.toFixed(2)}</b><br>Fuel Issued: <b>${f.toFixed(2)} L</b><br>Actual: <b>${a.toFixed(2)} L/HM</b>`} ['before','current','flowEnd'].forEach(id=>$(id).addEventListener('input',calc));
async function fileData(inp){let f=inp.files[0];if(!f)return null;return new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})}
async function saveTx(){let shift=JSON.parse(localStorage.getItem('shift')||'null');if(!shift)return alert('Mulai shift terlebih dahulu.');let required=['pUnit','pHm','pZero','pEnd'];if(required.some(x=>!$(x).files[0]))return alert('Empat foto wajib harus lengkap.');let b=+$('before').value,c=+$('current').value,z=+$('flow0').value,e=+$('flowEnd').value;if(!$('unit').value.trim())return alert('Kode unit wajib.');if(c<b)return alert('HM/KM Current tidak boleh lebih kecil dari Before.');if(z!==0)return alert('Flowmeter awal harus 0.');if(!(e>0))return alert('Flowmeter akhir harus lebih dari 0.');let now=new Date(),id='ABM-'+now.toISOString().slice(0,10).replaceAll('-','')+'-'+crypto.randomUUID().slice(0,8).toUpperCase();let tx={id,created:now.toISOString(),...shift,unit:$('unit').value.trim().toUpperCase(),before:b,current:c,total:c-b,flow0:z,fuel:e,actual:(c-b)>0?e/(c-b):0,status:'PENDING',photos:{unit:await fileData($('pUnit')),hm:await fileData($('pHm')),zero:await fileData($('pZero')),end:await fileData($('pEnd'))}};await new Promise((res,rej)=>{let r=db.transaction('tx','readwrite').objectStore('tx').put(tx);r.onsuccess=res;r.onerror=rej});alert('Transaksi tersimpan OFFLINE\n'+id);document.querySelectorAll('#tx input').forEach(x=>{if(x.type==='file')x.value='';else if(!['flow0'].includes(x.id))x.value=''});['sUnit','sHm','sZero','sEnd'].forEach(x=>{$(x).textContent='BELUM';$(x).style.color='#ffb3b3'});$('flow0').value='0';$('calc').innerHTML='';await counts();show('home')}
async function all(){return new Promise((res,rej)=>{let r=db.transaction('tx').objectStore('tx').getAll();r.onsuccess=()=>res(r.result);r.onerror=rej})}
async function render(){let a=(await all()).sort((x,y)=>y.created.localeCompare(x.created));$('rows').innerHTML=a.map(x=>`<div class='row'><b>${x.unit}</b> • ${x.fuel.toFixed(2)} L • ${x.truck}<br>${new Date(x.created).toLocaleString('id-ID')}<br><span class='${x.status==='SYNCED'?'synced':'pending'}'>${x.status}</span> • ${x.id}</div>`).join('')||'Belum ada transaksi.'}
async function counts(){let a=await all();$('pendingN').textContent=a.filter(x=>x.status!=='SYNCED').length;$('todayN').textContent=a.filter(x=>x.created.slice(0,10)===new Date().toISOString().slice(0,10)).length}
async function syncNow(){if(!navigator.onLine)return alert('Tidak ada internet. Data tetap aman di HP.');alert('Mode V1: endpoint server belum dipasang. Transaksi tetap PENDING dan aman di perangkat.');}
async function exportCSV(){let a=await all();let h=['Transaction_ID','Timestamp','Fuelman','Shift','Fuel_Truck','Unit','HM_Before','HM_Current','Total_HM_KM','Flowmeter_Start','Fuel_Issued_L','Actual_L_HM','Sync_Status'];let lines=[h.join(','),...a.map(x=>[x.id,x.created,x.fuelman,x.shift,x.truck,x.unit,x.before,x.current,x.total,x.flow0,x.fuel,x.actual.toFixed(2),x.status].join(','))];let blob=new Blob([lines.join('\n')],{type:'text/csv'}),u=URL.createObjectURL(blob),aEl=document.createElement('a');aEl.href=u;aEl.download='Refueling_Control_'+new Date().toISOString().slice(0,10)+'.csv';aEl.click();URL.revokeObjectURL(u)}
function net(){ $('net').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('net').style.background=navigator.onLine?'#16a34a':'#c2410c'}
window.addEventListener('online',net);window.addEventListener('offline',net);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');openDB().then(d=>{db=d;counts();net()});
