const $=id=>document.getElementById(id); let db;
const API_URL='https://script.google.com/macros/s/AKfycbzdVmDOpmxhiv3I22IPnTwrPDVZsKapb1j6Spgx7Jjuc2oMJoP8f0Gg_0D644pDJUd5yg/exec';
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function deviceId(){let id=localStorage.getItem('deviceId');if(!id){id='HP-'+crypto.randomUUID().slice(0,6).toUpperCase();localStorage.setItem('deviceId',id)}return id}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('RefuelDB',1);r.onupgradeneeded=e=>{if(!e.target.result.objectStoreNames.contains('tx'))e.target.result.createObjectStore('tx',{keyPath:'id'})};r.onsuccess=e=>{db=e.target.result;res(db)};r.onerror=rej})}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='history')render()}
function restoreProfile(){let s=JSON.parse(localStorage.getItem('shift')||'null');if(s){$('fuelman').value=s.fuelman||'';$('fuelmanId').value=s.fuelmanId||'';$('shift').value=s.shift||'DAY';$('truck').value=s.truck||'FT04';$('truckHmStart').value=s.truckHmStart??''}$('deviceLabel').textContent=deviceId();$('fuelmanIdLabel').textContent=s?.fuelmanId||'BELUM DISET'}
function startShift(){let fuelman=$('fuelman').value.trim(),fuelmanId=$('fuelmanId').value.trim().toUpperCase();if(!fuelman)return alert('Isi nama Fuelman.');if(!/^[A-Z0-9-]{2,12}$/.test(fuelmanId))return alert('Isi Fuelman ID, contoh FM01.');let truckHmStart=parseFloat($('truckHmStart').value);if(!Number.isFinite(truckHmStart)||truckHmStart<0)return alert('Isi HM/KM Awal Fuel Truck.');localStorage.setItem('shift',JSON.stringify({fuelman,fuelmanId,deviceId:deviceId(),shift:$('shift').value,truck:$('truck').value,truckHmStart}));restoreProfile();show('tx')}
['pUnit','pHm','pZero','pEnd'].forEach(id=>$(id).addEventListener('change',()=>{$('s'+id.slice(1)).textContent=$(id).files[0]?'SIAP ✓':'BELUM';$('s'+id.slice(1)).style.color=$(id).files[0]?'#4ade80':'#ffb3b3'}));
function calc(){let b=parseFloat($('before').value)||0,c=parseFloat($('current').value)||0,f=parseFloat($('flowEnd').value)||0;let d=c-b,a=d>0?f/d:0;$('calc').innerHTML=`Total HM/KM: <b>${d.toFixed(2)}</b><br>Fuel Issued: <b>${f.toFixed(2)} L</b><br>Actual: <b>${a.toFixed(2)} L/HM</b>`}['before','current','flowEnd'].forEach(id=>$(id).addEventListener('input',calc));
async function fileData(inp){let f=inp.files[0];if(!f)return null;return new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})}
function makeId(now,shift){let date=now.toISOString().slice(0,10).replaceAll('-','');let dev=(shift.deviceId||deviceId()).replace(/[^A-Z0-9]/g,'').slice(-6);let fm=(shift.fuelmanId||'FM').replace(/[^A-Z0-9]/g,'').slice(0,8);let rnd=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();return `ABM-${date}-${fm}-${dev}-${rnd}`}
async function saveTx(){let shift=JSON.parse(localStorage.getItem('shift')||'null');if(!shift)return alert('Mulai shift terlebih dahulu.');let required=['pUnit','pHm','pZero','pEnd'];if(required.some(x=>!$(x).files[0]))return alert('Empat foto wajib harus lengkap.');let b=+$('before').value,c=+$('current').value,z=+$('flow0').value,e=+$('flowEnd').value;if(!$('unit').value.trim())return alert('Kode unit wajib.');if(c<b)return alert('HM/KM Current tidak boleh lebih kecil dari Before.');if(z!==0)return alert('Flowmeter awal harus 0.');if(!(e>0))return alert('Flowmeter akhir harus lebih dari 0.');let now=new Date(),id=makeId(now,shift);let tx={id,created:now.toISOString(),...shift,deviceId:shift.deviceId||deviceId(),unit:$('unit').value.trim().toUpperCase(),before:b,current:c,total:c-b,flow0:z,fuel:e,actual:(c-b)>0?e/(c-b):0,status:'PENDING',photos:{unit:await fileData($('pUnit')),hm:await fileData($('pHm')),zero:await fileData($('pZero')),end:await fileData($('pEnd'))}};await new Promise((res,rej)=>{let r=db.transaction('tx','readwrite').objectStore('tx').put(tx);r.onsuccess=res;r.onerror=rej});alert('Transaksi tersimpan OFFLINE\n'+id);document.querySelectorAll('#tx input').forEach(x=>{if(x.type==='file')x.value='';else if(!['flow0'].includes(x.id))x.value=''});['sUnit','sHm','sZero','sEnd'].forEach(x=>{$(x).textContent='BELUM';$(x).style.color='#ffb3b3'});$('flow0').value='0';$('calc').innerHTML='';await counts();show('home')}
async function all(){return new Promise((res,rej)=>{let r=db.transaction('tx').objectStore('tx').getAll();r.onsuccess=()=>res(r.result);r.onerror=rej})}
async function render(){let a=(await all()).sort((x,y)=>y.created.localeCompare(x.created));$('rows').innerHTML=a.map(x=>`<div class='row'><b>${safe(x.unit)}</b> • ${Number(x.fuel).toFixed(2)} L • ${safe(x.truck)}<br>${new Date(x.created).toLocaleString('id-ID')}<br><span class='${x.status==='SYNCED'?'synced':'pending'}'>${safe(x.status)}</span> • ${safe(x.id)}<br><button class='detail-btn secondary' onclick="detail('${safe(x.id)}')">DETAIL & 4 FOTO</button></div>`).join('')||'Belum ada transaksi.'}
async function detail(id){let x=(await all()).find(t=>t.id===id);if(!x)return;let p=x.photos||{};let fig=(src,label)=>src?`<figure><img src='${src}' alt='${label}'><figcaption>${label} ✓</figcaption></figure>`:`<figure><figcaption>${label}: TIDAK TERSEDIA</figcaption></figure>`;$('detailBody').innerHTML=`<div class='meta'><b>${safe(x.id)}</b><br>Device: ${safe(x.deviceId||'-')} • Fuelman ID: ${safe(x.fuelmanId||'-')}<br>${safe(x.fuelman)} • ${safe(x.shift)} • ${safe(x.truck)}<br>Unit: <b>${safe(x.unit)}</b><br>HM/KM ${x.before} → ${x.current} | Total ${Number(x.total).toFixed(2)}<br>Fuel: <b>${Number(x.fuel).toFixed(2)} L</b> | Actual ${Number(x.actual).toFixed(2)} L/HM<br>Status: ${safe(x.status)}</div><div class='photo-grid'>${fig(p.unit,'① Kode Unit')}${fig(p.hm,'② HM/KM')}${fig(p.zero,'③ Flowmeter 0')}${fig(p.end,'④ Flowmeter Akhir')}</div>`;$('detailModal').classList.add('open')}
function closeDetail(){$('detailModal').classList.remove('open')}
async function counts(){let a=await all();$('pendingN').textContent=a.filter(x=>x.status!=='SYNCED').length;$('todayN').textContent=a.filter(x=>x.created.slice(0,10)===new Date().toISOString().slice(0,10)).length}
function putTx(x){return new Promise((res,rej)=>{let r=db.transaction('tx','readwrite').objectStore('tx').put(x);r.onsuccess=res;r.onerror=rej})}
async function shrinkPhoto(dataUrl){if(!dataUrl)return null;try{let blob=await (await fetch(dataUrl)).blob();let bmp=await createImageBitmap(blob);let max=1280,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));let c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72)}catch(e){return dataUrl}}
async function syncOne(x){let p=x.photos||{};let payload={action:'syncTransaction',version:'1.4',transaction:{...x,photos:{unit:await shrinkPhoto(p.unit),hm:await shrinkPhoto(p.hm),zero:await shrinkPhoto(p.zero),end:await shrinkPhoto(p.end)}}};let r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow'});if(!r.ok)throw new Error('HTTP '+r.status);let raw=await r.text(),j;try{j=JSON.parse(raw)}catch(e){throw new Error('Respons server bukan JSON')};if(j.success===false||j.status==='ERROR'||j.ok===false)throw new Error(j.message||'Server menolak transaksi');return j}
async function syncNow(){if(!navigator.onLine)return alert('Tidak ada internet. Data tetap aman di HP.');let btn=document.getElementById('syncBtn');if(btn){btn.disabled=true;btn.textContent='SYNC...'}let list=(await all()).filter(x=>x.status!=='SYNCED'),ok=0,fail=0,last='';if(!list.length){if(btn){btn.disabled=false;btn.textContent='SYNC SEKARANG'}return alert('Tidak ada transaksi pending.')}for(let x of list){try{let j=await syncOne(x);x.status='SYNCED';x.syncedAt=new Date().toISOString();x.serverResponse=j;await putTx(x);ok++}catch(e){fail++;last=e.message||String(e)}}await counts();await render();if(btn){btn.disabled=false;btn.textContent='SYNC SEKARANG'}alert('Sync selesai.\nBerhasil: '+ok+'\nBelum terkirim: '+fail+(last?'\n\nInfo terakhir: '+last:''));}
async function exportCSV(){let a=await all();let h=['Transaction_ID','Timestamp','Device_ID','Fuelman_ID','Fuelman','Shift','Fuel_Truck','FT_HM_KM_Start','Unit','HM_Before','HM_Current','Total_HM_KM','Flowmeter_Start','Fuel_Issued_L','Actual_L_HM','Sync_Status'];let q=v=>'"'+String(v??'').replaceAll('"','""')+'"';let lines=[h.join(','),...a.map(x=>[x.id,x.created,x.deviceId||'',x.fuelmanId||'',x.fuelman,x.shift,x.truck,x.truckHmStart??'',x.unit,x.before,x.current,x.total,x.flow0,x.fuel,x.actual.toFixed(2),x.status].map(q).join(','))];let blob=new Blob([lines.join('\n')],{type:'text/csv'}),u=URL.createObjectURL(blob),aEl=document.createElement('a');aEl.href=u;aEl.download='Refueling_Control_'+new Date().toISOString().slice(0,10)+'.csv';aEl.click();URL.revokeObjectURL(u)}
function net(){$('net').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('net').style.background=navigator.onLine?'#16a34a':'#c2410c'}
window.addEventListener('online',net);window.addEventListener('offline',net);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');openDB().then(d=>{db=d;restoreProfile();counts();net()});
